### ISSUE TITLE
create_folders.sh and cron_sa_learn.sh skip mailbox of domain owner

### ISSUE THREAD

**Issue by jobhh** [poralix/directadmin-teach-sa#1]
I've ran the create_folders.sh script and it skips the mailboxes of domain owners. So the users who log in to their mailbox with the username *domainowner* instead of *mailbox*@*domainname*.com. It gives a warning if a domainname has no mailboxes (other than the domainowner), because it doesn't find any mailboxes. If a domainname has mailboxes, no warning is given and the .teach-is(not)spam folders are created, but the domainowner mailbox is skipped.

cron_sa_learn.sh also skips the mailboxes of the domain owners.

The WARNING message when no mailboxes are found at a domain:

    root@web3:/usr/local/directadmin/scripts/custom/directadmin-teach-sa# ./create_folders.sh --all
    [Sat Sep  9 14:15:37 CEST 2017] [OK] Domain *domainname*.com owned by user *domainowner*
    [Sat Sep  9 14:15:37 CEST 2017] [OK] Found imap folder /home/*domainowner*/imap/*domainname*.com/
    [Sat Sep  9 14:15:37 CEST 2017] [WARNING] Password file found but is empty for the domain *domainname*.com. Skipping...

For normal mailboxes like wiki@*domainname*.com it does create the folders:

    [Sat Sep  9 14:15:37 CEST 2017] [OK] Found maildir for wiki in /home/*domainowner*/imap/*domainname*.com/wiki/Maildir
    [Sat Sep  9 14:15:37 CEST 2017] [OK] [+] Creating directory /home/*domainowner*/imap/*domainname*.com/wiki/Maildir/.INBOX.teach-isspam/
    [Sat Sep  9 14:15:37 CEST 2017] [OK] [+] Created /home/*domainowner*/imap/*domainname*.com/wiki/Maildir/.INBOX.teach-isspam/
    [Sat Sep  9 14:15:37 CEST 2017] [OK] [+] Updating subscriptions
    [Sat Sep  9 14:15:37 CEST 2017] [OK] [+] Creating directory /home/*domainowner*/imap/*domainname*.com/wiki/Maildir/.INBOX.teach-isnotspam/
    [Sat Sep  9 14:15:37 CEST 2017] [OK] [+] Created /home/*domainowner*/imap/*domainname*.com/wiki/Maildir/.INBOX.teach-isnotspam/
    [Sat Sep  9 14:15:37 CEST 2017] [OK] [+] Updating subscriptions

**Comment by poralix** [comment]
Hello,

Thank you for your report. I will check it and update you with my findings soon.

Regards,
Alex.

**Comment by poralix** [comment]
It should be fixed now. I've updated code and uploaded v.0.2. Please check it and let me know your results.

**Comment by jobhh** [comment]
create_folders.sh and cron_sa_learn.sh now seem to include the system accounts. Functionally it's fine now, thanks!  :)

If I'm allowed to nitpick: In the output of create_folders.sh there are quite some 'warnings', which aren't really warning worthy I think. And one in cron_sa_learn.sh I'd like to mention.

1. cron_sa_learn.sh - This warning was there before the update as well, it only happens at the admin user.

       [Tue Sep 12 12:45:29 CEST 2017] [OK] Started!
       [Tue Sep 12 12:45:29 CEST 2017] [INFO] Running ./cron_sa_learn.sh as user root
       [Tue Sep 12 12:45:29 CEST 2017] [OK] The binary sudo was found
       [Tue Sep 12 12:45:29 CEST 2017] [OK] Running for user admin
       [Tue Sep 12 12:45:29 CEST 2017] [OK] [admin] [+] found system mail account in /home/admin/Maildir
       0.000          0          3          0  non-token data: bayes db version
       0.000          0          0          0  non-token data: nspam
       0.000          0          0          0  non-token data: nham
       0.000          0          0          0  non-token data: ntokens
       0.000          0          0          0  non-token data: oldest atime
       0.000          0          0          0  non-token data: newest atime
       0.000          0          0          0  non-token data: last journal sync atime
       0.000          0          0          0  non-token data: last expiry atime
       0.000          0          0          0  non-token data: last expire atime delta
       0.000          0          0          0  non-token data: last expire reduction count
       ls: cannot access '/home/admin/imap': No such file or directory

2. create_folders.sh - It still gives a "Password file found but is empty" warning when no 'normal' mailboxes are found. A notice or more descriptive message might be better, since I don't think it's rare to only have the primary system user mailbox.

       [Tue Sep 12 12:30:13 CEST 2017] [OK] Found imap folder /home/*username*/imap/*2nddomain*.com/
       [Tue Sep 12 12:30:13 CEST 2017] [WARNING] Password file found but is empty for the domain *2nddomain*.com. Skipping...

3. create_folders.sh - When a user has multiple domains it will create the folders the first time, but for the other domains the same user owns it gives warnings. It might confuse people running the script for the first time.

       [Tue Sep 12 12:30:13 CEST 2017] [OK] Domain *2nddomain*.com owned by user *username*
       [Tue Sep 12 12:30:13 CEST 2017] [OK] Processing system mail account for user *username* (i.e. *username*@*server*.com)
       [Tue Sep 12 12:30:13 CEST 2017] [WARNING] [-] Directory /home/*username*/Maildir/.INBOX.teach-isspam/ already exists, skipping...
       [Tue Sep 12 12:30:13 CEST 2017] [WARNING] [-] Skipping subscriptions. Already exists...
       [Tue Sep 12 12:30:13 CEST 2017] [WARNING] [-] Directory /home/*username*/Maildir/.INBOX.teach-isnotspam/ already exists, skipping...
       [Tue Sep 12 12:30:13 CEST 2017] [WARNING] [-] Skipping subscriptions. Already exists...

**Comment by poralix** [comment]
Thanks for your comments. Please try it now. I've updated the scripts.

**Comment by jobhh** [comment]
Quite some NOTICE's now when creating the folders, since all the folders already exist. So that's fine :)

However! Running ./cron_sa_learn.sh > ./cron_sa_learn.log 2>&1 results in a very small cron_sa_learn.log file:

    ./cron_sa_learn.sh: line 180: syntax error near unexpected token `done'
    ./cron_sa_learn.sh: line 180: `    done;'

**Comment by poralix** [comment]
My apologizes for the typo in the script. It should be fixed now in v.0.4. The _cron_sa_learn.sh_ is now more optimized. We skip running _sa-learn_ for empty folders now, and it allowed to increase significantly the execution speed.

Please try it now.

**Comment by jobhh** [comment]
seems to be working :)
