### ISSUE TITLE
Overfitting question and feature requests

### ISSUE THREAD

**Issue by jobhh** [poralix/directadmin-teach-sa#2]
I'm wondering what happens if I do not empty the INBOX.teach-isspam and INBOX.teach-isnotspam folders. Are the messages that were already in there ignored during the next training rounds? Otherwise the Bayesian network should start overfitting on that limited data set right?

Feature requests:
1. If it is not like this by default: Add an option to ignore emails that were already present in the INBOX.teach-is(not)spam folders during the previous training round without removing them. So only train on new emails.
2. Add an option to move the content of INBOX.teach-isnotspam to the INBOX after it is processed.
3. Option to mark all e-mails as read in the spam folders.

**Comment by poralix** [comment]
Hello,

Here is what the **sa-learn** documentation says:

> SpamAssassin remembers which mail messages it has learnt already, and will not re-learn those messages again.... Messages learnt as spam will have SpamAssassin markup removed, on the fly.
> 
> If you make a mistake and scan a mail as ham when it is spam, or vice versa, simply rerun this command with the correct classification, and the mistake will be corrected.  SpamAssassin will automatically ’forget’ the previous indications.

So there is no need to change anything.

As of

> Add an option to move the content of INBOX.teach-isnotspam to the INBOX after it is processed.

Why do you need it? 

It's expected that users copy (not move) emails from INBOX into INBOX.teach-isnotspam.

> Option to mark all e-mails as read in the spam folders.

Why do you need it? 

Regards,
Alex.

**Comment by jobhh** [comment]
> It's expected that users copy (not move) emails from INBOX into INBOX.teach-isnotspam.

Ok, that's fine.

> Option to mark all e-mails as read in the spam folders.

It's just 1 action less when handling spam messages I can't think of a use case spam should remain unread. But if it's a hassle don't put time in it :)

**Comment by jobhh** [comment]
I just figured out my current scenario is one where the "Option to mark all e-mails as read in the spam folders." is actually useful.

For some reason the 0teach_sa.cron in /etc/cron.d/ does not seem to run. Running the script manually works fine. If all messages scanned for SPAM/HAM would be marked as read that is a subtle indication for everyone that the emails they moved are being processed :) And for me as the guy running the server it's a clear indication when the script has been executed, or not.

I assume the lack of execution from the cron.d file is not related to your script, so I'll toy with it when I get the time.

Edit:
0teach_sa.cron not running might be due to this. I've renamed the file to teach_sa, I'll let you know if it runs in the coming days.

    Files must conform to the same naming convention as used by run-parts(8): they must consist solely of upper- and lower-case letters, digits, underscores, and hyphens.

**Comment by jobhh** [comment]
I've created 2 separate tickets for the 2 issues I've encountered to keep this one about my feature request. 

I think it would be helpful if processed mails would be marked as read, since this gives the user some feeling moving the mails works and the admin has an easy check to see if the mail is actually processed. If you don't agree this ticket can be closed :)

**Comment by poralix** [comment]
Thanks. Kindly check v.0.5 and settings.cnf.default for new settings, copy them with your values to settings.cnf:

```
# TO DELETE OR NOT EMAIL AFTER TEACHING SPAM
DELETE_TEACH_SPAM_DATA="0";

# TO DELETE OR NOT EMAIL AFTER TEACHING NOT SPAM
DELETE_TEACH_HAM_DATA="0";

# TO MARK AS READ OR NOT EMAIL AFTER TEACHING SPAM
# DELETE_TEACH_SPAM_DATA SHOULD BE SET TO 0
MARK_AS_READ_TEACH_SPAM_DATA="1";

# TO MARK AS READ OR NOT EMAIL AFTER TEACHING NOT SPAM
# DELETE_TEACH_HAM_DATA SHOULD BE SET TO 0
MARK_AS_READ_TEACH_HAM_DATA="1";
```


Regards,
Alex.

**Comment by jobhh** [comment]
Haven't been able to check it yet due to the permission error from SpamAssassin. I will probably get to it somewhere in November.

**Comment by jobhh** [comment]
The log says it is marking emails as read, but it doesn't seem to actually do it.

    [Wed Nov  8 04:05:30 CET 2017] [OK] [username] [+] Marking emails as read in /home/username/imap/username.com/mailbox/Maildir/.INBOX.teach-isspam/new/
    [Wed Nov  8 04:05:30 CET 2017] [OK] [username] [+] Marking emails as read in /home/username/imap/username.com/mailbox/Maildir/.INBOX.teach-isspam/cur/

![image](https://user-images.githubusercontent.com/2331451/32723909-8362dcf8-c86f-11e7-833d-cd97088b250d.png)

Edit:
I'll make this a separate issue.
