### ISSUE TITLE
cronjob won't run due to naming

### ISSUE THREAD

**Issue by jobhh** [poralix/directadmin-teach-sa#4]
As mentioned in https://github.com/poralix/directadmin-teach-sa/issues/2, the cronjob didn't run when I copied it as 0teach_sa.cron to /etc/cron.d/. It did run when I renamed it to something without a dot.

I found this text online: 

    Files must conform to the same naming convention as used by run-parts(8): they must consist solely of upper- and lower-case letters, digits, underscores, and hyphens.

**Comment by poralix** [comment]
Hello,

Thanks for reporting. Renamed.

Regards,
Alex.
