### ISSUE TITLE
Website update and #2 and #3 responses

### ISSUE THREAD

**Issue by jobhh** [poralix/directadmin-teach-sa#5]
The article on https://help.poralix.com/articles/teaching-spamassassin-on-directadmin-servers-with-sa-learn has an outdated settings.cnf and the outdated name of the cron file:

    cp -p ./0teach_sa.cron /etc/cron.d/

Also, I'm not sure if you get a notification when a closed issue gets a new response on Github. If you do, my apologies. I also seem unable to reopen the issues.

Hereby a quick notification that I've replied in #3 (with my analysis and suggested fix) and #2 (with a very undetailed bug report).

**Comment by poralix** [comment]
Hello,

Thanks. It's corrected now.

Regards,
Alex,
