### ISSUE TITLE
Would this also work with rspamd?

### ISSUE THREAD

**Issue by TLWebdesign** [poralix/directadmin-teach-sa#9]
Hi,

I have had this sa-learn on my old server using spamassassin. Now i'm setting up a new server using rspamd with your gui (thanks for that :)). and now i'm wondering if there is a rspamd alternative to this. Or would this just work regardless of spamassassin or rspamd? 

Kind regards
Tom

**Comment by gralex54** [comment]
Hello Tom,

Thank you for the inquiry. Will you give a version 0.10 a try.

v0.10: A support for Rspamd added (beta)

Regards,
Alex.

**Comment by TLWebdesign** [comment]
Hi,

Cool great news! I'll test it out somewhere in next weeks on the new test server we've been setting up.

Will report back if I find any issues. 

Kind regards,
Tom

**Comment by gralex54** [comment]
As no new issues has ever been reported, I believe it's working fine. I'm closing it.
